#!/usr/bin/env bash

set -uo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"

# shellcheck source=tests/lib/install_test_support.sh
source "$ROOT/tests/lib/install_test_support.sh"
# shellcheck source=tests/install/01_staged.sh
source "$ROOT/tests/install/01_staged.sh"
# shellcheck source=tests/install/02_live_quiesce.sh
source "$ROOT/tests/install/02_live_quiesce.sh"
# shellcheck source=tests/install/03_setup_and_staged_contracts.sh
source "$ROOT/tests/install/03_setup_and_staged_contracts.sh"
# shellcheck source=tests/install/04_docs_and_contracts.sh
source "$ROOT/tests/install/04_docs_and_contracts.sh"
# shellcheck source=tests/install/05_guard_cleanup.sh
source "$ROOT/tests/install/05_guard_cleanup.sh"
run_test() {
  local name="$1" rc
  shift
  printf 'TEST %s ... ' "$name"
  "$@"
  rc=$?
  case "$rc" in
    0)
      passes=$((passes + 1))
      printf 'ok\n'
      ;;
    77)
      skips=$((skips + 1))
      printf 'skipped\n'
      ;;
    *)
      failures=$((failures + 1))
      printf 'not ok\n'
      ;;
  esac
}

run_test default_staged_install_from_unrelated_cwd test_default_staged_install_from_unrelated_cwd
run_test staged_managed_profile_artifacts_have_exact_content_and_modes test_staged_managed_profile_artifacts_have_exact_content_and_modes
run_test new_sources_and_targets_are_preflighted_before_staging_mutation test_new_sources_and_targets_are_preflighted_before_staging_mutation
run_test installer_preserves_api_credential_pre_managed_snapshot_and_state test_installer_preserves_api_credential_pre_managed_snapshot_and_state
run_test zero_args_and_explicit_wg0_are_compatible test_zero_args_and_explicit_wg0_are_compatible
run_test custom_interface_uses_an_exact_filename test_custom_interface_uses_an_exact_filename
run_test invalid_cli_is_rejected_before_writes test_invalid_cli_is_rejected_before_writes
run_test live_install_requires_root test_live_install_requires_root
run_test unsafe_destdir_values_are_rejected test_unsafe_destdir_values_are_rejected
run_test missing_sources_fail_before_staging_mutation test_missing_sources_fail_before_staging_mutation
run_test existing_healthcheck_config_is_preserved_and_tightened test_existing_healthcheck_config_is_preserved_and_tightened
run_test existing_wireguard_config_is_never_overwritten test_existing_wireguard_config_is_never_overwritten
run_test writable_existing_config_is_rejected_without_changes test_writable_existing_config_is_rejected_without_changes
run_test managed_symlink_target_is_rejected_and_untouched test_managed_symlink_target_is_rejected_and_untouched
run_test nonregular_managed_target_is_rejected_before_mutation test_nonregular_managed_target_is_rejected_before_mutation
run_test atomic_replacement_failure_preserves_old_file test_atomic_replacement_failure_preserves_old_file
run_test atomic_interruption_cleans_temp_without_leaking_traps test_atomic_interruption_cleans_temp_without_leaking_traps
run_test artifact_failure_is_ordered_and_safely_retryable test_artifact_failure_is_ordered_and_safely_retryable
run_test managed_artifact_install_order_is_dependency_safe test_managed_artifact_install_order_is_dependency_safe
run_test existing_managed_file_owner_is_not_blessed test_existing_managed_file_owner_is_not_blessed
run_test systemctl_behavior_is_explicit_and_exact test_systemctl_behavior_is_explicit_and_exact
run_test quiesce_argument_matrix_is_explicit_and_staging_is_rejected test_quiesce_argument_matrix_is_explicit_and_staging_is_rejected
run_test ordinary_live_upgrade_refuses_an_active_worker_before_mutation test_ordinary_live_upgrade_refuses_an_active_worker_before_mutation
run_test ordinary_live_upgrade_refuses_an_active_timer_before_mutation test_ordinary_live_upgrade_refuses_an_active_timer_before_mutation
run_test ordinary_live_upgrade_refuses_a_held_interface_lock test_ordinary_live_upgrade_refuses_a_held_interface_lock
run_test live_upgrade_refuses_pending_journal_or_safety_record test_live_upgrade_refuses_pending_journal_or_safety_record
run_test quiesce_stops_waits_checks_and_leaves_timer_disabled test_quiesce_stops_waits_checks_and_leaves_timer_disabled
run_test systemctl_inactive_query_errors_fail_closed test_systemctl_inactive_query_errors_fail_closed
run_test inactive_status_with_stderr_diagnostic_fails_closed test_inactive_status_with_stderr_diagnostic_fails_closed
run_test quiesce_timer_enable_state_is_exact_and_fail_closed test_quiesce_timer_enable_state_is_exact_and_fail_closed
run_test quiesce_rejects_enabled_state_with_stderr_diagnostic_before_disable test_quiesce_rejects_enabled_state_with_stderr_diagnostic_before_disable
run_test live_upgrade_refuses_active_or_unqueryable_shared_instances test_live_upgrade_refuses_active_or_unqueryable_shared_instances
run_test upgrade_locks_are_retained_and_released_for_the_selected_interface test_upgrade_locks_are_retained_and_released_for_the_selected_interface
run_test upgrade_locks_migrate_only_safe_empty_legacy_mode test_upgrade_locks_migrate_only_safe_empty_legacy_mode
run_test upgrade_locks_refuse_held_wg1_lock_or_unsafe_setup_guard test_upgrade_locks_refuse_held_wg1_lock_or_unsafe_setup_guard
run_test reentrant_upgrade_lock_acquisition_preserves_the_first_lease test_reentrant_upgrade_lock_acquisition_preserves_the_first_lease
run_test upgrade_runtime_directory_rejects_an_unsafe_destdir_run_parent test_upgrade_runtime_directory_rejects_an_unsafe_destdir_run_parent
run_test quiesce_partial_failure_keeps_timer_disabled_and_reports_it test_quiesce_partial_failure_keeps_timer_disabled_and_reports_it
run_test main_quiesce_failure_after_preparation_keeps_timer_disabled_and_releases_locks test_main_quiesce_failure_after_preparation_keeps_timer_disabled_and_releases_locks
run_test state_directory_creation_failure_aborts_layout test_state_directory_creation_failure_aborts_layout
run_test setup_package_manifest_rejects_unexpected_entries_and_links test_setup_package_manifest_rejects_unexpected_entries_and_links
run_test setup_upgrade_guard_is_published_before_package_and_retained_on_failure test_setup_upgrade_guard_is_published_before_package_and_retained_on_failure
run_test dual_entrypoint_guards_publish_before_any_dependency_mutation test_dual_entrypoint_guards_publish_before_any_dependency_mutation
run_test guarded_publication_failures_keep_runtime_guarded_and_stop_later_actions test_guarded_publication_failures_keep_runtime_guarded_and_stop_later_actions
run_test installer_exit_cleanup_releases_locks_preserves_signal_and_does_not_leak_traps test_installer_exit_cleanup_releases_locks_preserves_signal_and_does_not_leak_traps
run_test staged_enable_never_calls_host_systemctl test_staged_enable_never_calls_host_systemctl
run_test safe_inert_environment_template test_safe_inert_environment_template
run_test installer_declares_exact_mode_contract test_installer_declares_exact_mode_contract
run_test authenticated_telemetry_and_command_hooks_are_retired test_authenticated_telemetry_and_command_hooks_are_retired
run_test service_environment_and_hardening_contract test_service_environment_and_hardening_contract
run_test readme_documents_dual_mode_quick_paths_and_manual_timer_decision test_readme_documents_dual_mode_quick_paths_and_manual_timer_decision
run_test operations_upgrade_quiesces_before_install_and_preserves_recovery_state test_operations_upgrade_quiesces_before_install_and_preserves_recovery_state
run_test operations_package_uninstall_quiesces_every_instance_and_preserves_pending_state test_operations_package_uninstall_quiesces_every_instance_and_preserves_pending_state
run_test operations_rollback_masks_legacy_auto_enable_until_validation test_operations_rollback_masks_legacy_auto_enable_until_validation
run_test operations_credential_removal_is_explicit_and_uninstall_preserves_recovery_data test_operations_credential_removal_is_explicit_and_uninstall_preserves_recovery_data
run_test python_bytecode_is_ignored test_python_bytecode_is_ignored
run_test repository_text_uses_lf_on_every_platform test_repository_text_uses_lf_on_every_platform
run_test public_repository_docs_are_sanitized_and_complete test_public_repository_docs_are_sanitized_and_complete
run_test ci_workflow_is_deterministic_and_smoke_isolated test_ci_workflow_is_deterministic_and_smoke_isolated

printf '\nInstaller tests: %d passed, %d skipped, %d failed\n' "$passes" "$skips" "$failures"
(( failures == 0 ))
