#!/usr/bin/env bash

# Explicit, path-independent runner for the wg-healthcheck shell suite.
# shellcheck disable=SC1090,SC2016,SC2034,SC2064,SC2123,SC2153,SC2163,SC2317,SC2329

set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$ROOT/bin/wg-healthcheck"
VERSION_FILE="$ROOT/VERSION"

source "$ROOT/tests/lib/wg_healthcheck_test_support.sh"
source "$ROOT/tests/wg_healthcheck/group_01.sh"
source "$ROOT/tests/wg_healthcheck/group_02.sh"
source "$ROOT/tests/wg_healthcheck/group_03.sh"
source "$ROOT/tests/wg_healthcheck/group_04.sh"
source "$ROOT/tests/wg_healthcheck/group_05.sh"

tests=(
  test_version_output_is_fixed_and_public
  test_sourceable_without_executing_or_enabling_errexit
  test_runtime_cli_preserves_legacy_version_and_rejects_unknown_forms
  test_setup_lease_cli_is_explicit_scoped_and_fd_distinct
  test_mutating_cli_requires_exactly_one_mode_and_scopes_options
  test_settings_descriptor_is_exact_stable_private_and_canonical
  test_main_captures_settings_before_context_and_overlays_only_memory
  test_main_sanitizes_before_settings_metadata_children
  test_second_sanitizer_failure_closes_restored_credential_fd
  test_runtime_defaults_and_fixed_paths_ignore_environment
  test_process_environment_is_sanitized_for_child_commands
  test_hostile_internal_paths_cannot_redirect_main_or_truncate_lock_target
  test_main_validates_both_fixed_files_before_parsing_config
  test_config_parser_accepts_template_and_whole_quoted_values
  test_config_parser_rejects_internal_unknown_duplicate_and_malformed_keys
  test_config_parser_rejects_ambiguous_syntax_without_execution_or_partial_apply
  test_config_parser_rejects_oversized_file_and_line
  test_api_settings_require_device_allowed_port_and_normalize_countries
  test_managed_qb_container_name_rejects_exact_immutable_id_without_static_regression
  test_restart_cooldown_prevents_every_rotation_side_effect
  test_exact_endpoint_mismatch_rolls_back_and_verifies_qbittorrent
  test_rotation_stamp_is_written_only_after_every_postcondition
  test_two_peer_config_is_rejected_without_changes
  test_backup_path_is_stable_bounded_and_replaced_atomically
  test_first_slow_then_good_speed_sample_does_not_rotate
  test_two_slow_speed_samples_rotate_exactly_once
  test_qbittorrent_restart_rechecks_and_fails_when_socket_is_still_missing
  test_required_rule_is_a_mandatory_tunnel_postcondition
  test_selector_failure_restarts_current_endpoint_but_returns_degraded
  test_selector_restart_failure_is_never_reported_as_success
  test_malformed_selector_contract_restarts_current_endpoint_degraded
  test_rollback_up_failure_is_logged_and_nonzero
  test_failed_post_rotation_speed_probe_rolls_back_once
  test_status_file_is_atomic_private_and_machine_readable
  test_restart_attempt_stamp_precedes_fixed_down_and_up
  test_legacy_authenticated_telemetry_remains_retired
  test_strict_ip_and_peer_section_validation
  test_handshake_age_parses_wireguard_columns
  test_three_state_cooldown_and_invalid_restart_state
  test_rotation_cooldown_distinguishes_suppression_from_corruption
  test_rotation_disabled_speed_restart_and_failure_status
  test_fixed_command_wrappers_pass_exact_argv
  test_main_uses_root_seam_and_validates_both_files
  test_setup_guard_precedes_context_and_stale_context_is_never_loaded_on_contention
  test_main_keeps_credential_private_during_pre_guard_context
  test_setup_guard_is_private_nofollow_and_validates_exclusive_inherited_lease
  test_setup_lease_validation_helpers_inherit_no_other_private_descriptors
  test_main_lock_contention_is_nonblocking_and_side_effect_free
  test_explicit_lock_contention_is_busy_and_closes_credential_descriptors
  test_load_command_context_allows_profile_independent_commands_to_lack_profile
  test_static_no_marker_never_touches_credential_provider_or_managed_code
  test_static_selector_validates_provider_only_when_selection_is_needed
  test_pending_marker_classification_loads_only_the_required_owner
  test_v1_static_dispatch_reconciles_without_loading_managed_runtime
  test_main_propagates_route_rule_and_qbittorrent_failures
  test_main_rejects_invalid_speed_stamp
  test_restart_rejects_invalid_speed_mode_before_commands
  test_each_rotation_postcondition_failure_rolls_back
  test_pending_rotation_is_reconciled_before_health_checks
  test_failed_pending_reconciliation_retains_marker
  test_rollback_rotate_stamp_removal_failure_retains_pending_state
  test_reconciliation_rotate_stamp_removal_failure_retains_pending_state
  test_pending_marker_prevents_backup_overwrite
  test_main_reconciles_pending_state_before_normal_health
  test_interruption_handler_retains_marker_and_installs_traps
  test_interruption_handler_is_child_free_with_untracked_private_descriptors
  test_durability_barriers_cover_transaction_and_cleanup_order
  test_backup_barrier_failure_prevents_unmarked_mutation
  test_marker_barrier_failure_retains_recovery_state
  test_config_barrier_failure_performs_verified_rollback
  test_marker_cleanup_barrier_failure_recreates_recovery_marker
  test_secure_helper_and_parent_validation
  test_static_settings_do_not_touch_provider_helper
  test_route_and_rule_checks_consume_large_producer_output
  test_canonical_endpoint_equivalence_is_used_everywhere
  test_qbittorrent_binding_requires_tcp_udp_process_and_container_pid
  test_https_curl_policy_and_egress_cleanup
  test_speed_failure_reason_is_truthful
  test_selector_failures_use_one_protective_restart_owner
  test_timer_health_speed_and_qb_failures_dispatch_managed_rotation_in_api_mode
  test_timer_failures_keep_static_endpoint_dispatch_in_static_mode
  test_api_rotation_disabled_is_restart_only_and_managed_failure_never_falls_through
  test_admin_commands_refuse_pending_state_without_reconciliation_effects
  test_status_main_path_is_observational_and_creates_no_runtime_files
  test_interface_lock_open_is_nofollow_private_and_never_truncates_symlink_target
  test_core_dump_suppression_precedes_context_and_closes_credential_on_failure
  test_reset_context_allows_genuinely_missing_profile_but_not_symlink
  test_status_context_validates_existing_state_directory_without_repair
  test_context_refuses_untrusted_config_parent_before_file_or_parse
)


if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  if [[ -n "${WG_HEALTHCHECK_TEST_ONLY:-}" ]]; then
    read -r -a tests <<< "$WG_HEALTHCHECK_TEST_ONLY"
  fi

  failures=0
  for test_name in "${tests[@]}"; do
    if ("$test_name"); then
      printf 'ok - %s\n' "$test_name"
    else
      printf 'not ok - %s\n' "$test_name"
      failures=$((failures + 1))
    fi
  done

  if (( failures > 0 )); then
    printf '%d test(s) failed\n' "$failures" >&2
    exit 1
  fi

  printf '%d test(s) passed\n' "${#tests[@]}"
fi
